// src/App.jsx
import { useState, useRef, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import icon from './favicon2.png'; 
import universities from '/data/universities';
import quizQuestions from '/data/quizQuestions';
import SearchBar from '/components/SearchBar';

function App() {
  const [searchText, setSearchText] = useState("");
  const [searched, setSearched] = useState(false);
  const [results, setResults] = useState([]);
  const [selectedUniversity, setSelectedUniversity] = useState(null);
  const [glow, setGlow] = useState(false);
  const [darkMode, setDarkMode] = useState(null);
  const [ready, setReady] = useState(false);
  const [displayedSubtitle, setDisplayedSubtitle] = useState("");
  const [showQuiz, setShowQuiz] = useState(false);
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [quizScores, setQuizScores] = useState({});
  const [quizResult, setQuizResult] = useState(null);
  const [salaryRange, setSalaryRange] = useState(5000);
  const inputRef = useRef(null);

  useEffect(() => {
    const savedMode = localStorage.getItem("darkMode");
    setDarkMode(savedMode === "true");
    setReady(true);
  }, []);

  useEffect(() => {
    if (selectedUniversity || showQuiz) {
      const closeMenuEsc = (event) => {
        if (event.key === 'Escape') {
          if (selectedUniversity) {
            setSelectedUniversity(null);
          }
          if (showQuiz) {
            closeQuiz();
          }
          }
      };

      document.addEventListener('keydown', closeMenuEsc);

      return () => {
       document.removeEventListener('keydown', closeMenuEsc);
      };
    }
  }, [selectedUniversity, showQuiz]);

  useEffect(() => {
    if (!searched && !showQuiz) {
      const text1 = "INFORMAȚII DESPRE FACULTĂȚI ȘI JOBURI";
      const text2 = "GĂSEȘTE-ȚI FACULTATEA PERFECTĂ";
      let textToType = text1;
      let isTyping = true;
      let i = 0;
      let interval;
      let timeout;

      const type = () => {
        interval = setInterval(() => {
          if (isTyping) {
            setDisplayedSubtitle(textToType.slice(0, i));
            i++;
            if (i > textToType.length) {
              clearInterval(interval);
              timeout = setTimeout(erase, 3000);
            }
          }
        }, 50);
      };

      const erase = () => {
        isTyping = false;
        let j = textToType.length;
        interval = setInterval(() => {
          setDisplayedSubtitle(textToType.slice(0, j));
          j--;
          if (j < 0) {
            clearInterval(interval);
            textToType = textToType === text1 ? text2 : text1;
            i = 0;
            isTyping = true;
            timeout = setTimeout(type, 50);
          }
        }, 25);
      };

      type();

      return () => {
        clearInterval(interval);
        clearTimeout(timeout);
      };
    } else {
      setDisplayedSubtitle("INFORMAȚII DESPRE FACULTĂȚI ȘI JOBURI");
    }
  }, [searched, showQuiz]);

  if (!ready) return null;

  const toggleDarkMode = () => {
    setDarkMode((prev) => {
      localStorage.setItem("darkMode", !prev);
      return !prev;
    });
  };

  const logoClick = () => {
    setGlow(true);
    setTimeout(() => {
      window.location.reload();
    }, 350);
  };

  const InfoCard = ({ title, icon, children }) => (
    <div className={`p-6 rounded-2xl shadow-lg mt-4 w-full ${darkMode ? 'bg-slate-800 text-white' : 'bg-gray-100 text-gray-900'}`}>
        <div className="flex items-center mb-2">
            <span className={`p-2 rounded-full mr-3 ${darkMode ? 'bg-slate-700' : 'bg-gray-300'}`}>
              {icon}
            </span>
            <h4 className="font-semibold text-lg">{title}</h4>
        </div>
        {children}
    </div>
  );

  const quizAnswer = (scores) => {
    const newScores = { ...quizScores };
    for (const faculty in scores) {
      newScores[faculty] = (newScores[faculty] || 0) + scores[faculty];
    }
    setQuizScores(newScores);

    const nextQuestionIndex = currentQuestionIndex + 1;
    if (nextQuestionIndex < quizQuestions.length) {
      setCurrentQuestionIndex(nextQuestionIndex);
    } else {
      calculateResult();
    }
  };

  const calculateResult = () => {
    let bestFit = null;
    let maxScore = -1;

    universities.forEach(f => {
      const score = quizScores[f.name] || 0;
      if (score > maxScore) {
        maxScore = score;
        bestFit = f;
      }
    });

    if (bestFit && salaryRange > bestFit.salary.max) {
      setQuizResult({
        name: "Atenție: Salariul dorit este prea mare pentru interesele tale",
        details: {
          study: `Conform răspunsurilor tale, cea mai bună alegere ar fi ${bestFit.name}. Totuși, salariul maxim oferit în acest domeniu este de ${bestFit.salary.max} RON, sub salariul de ${salaryRange} RON pe care îl vrei. Poți reconsidera fie salariul, fie domeniul.`,
        },
      });
    } else if (bestFit) {
      setQuizResult(bestFit);
    } else {
      setQuizResult({
        name: "EROARE: Nu s-a găsit nicio recomandare!",
        details: {
          study: "EROARE: Nu s-a putut găsi o recomandare bazată pe răspunsurile tale."
        }
      });
    }
  };

  const startQuiz = () => {
    setShowQuiz(true);
    setQuizScores({});
    setCurrentQuestionIndex(0);
    setQuizResult(null);
  };

  const closeQuiz = () => {
    setShowQuiz(false);
    setQuizResult(null);
  };

  const currentQuestion = quizQuestions[currentQuestionIndex];

  return (
    <div
      className={`min-h-screen w-screen flex flex-col transition-all duration-700 select-none ${
        darkMode ? "bg-[#0F172A] text-white" : "bg-[#F1F5F9] text-gray-900"
      }`}
    >
      <button
        className={`fixed top-4 right-4 p-2 rounded-full ${
          darkMode ? 'bg-cyan-700 text-white'
          : 'bg-cyan-500 text-white'} shadow-lg hover:shadow-xl z-50`}
        onClick={toggleDarkMode}
      >
        {darkMode ? (
            <svg xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24" 
              fill="none" 
              stroke="currentColor" 
              strokeWidth="2" 
              strokeLinecap="round" 
              strokeLinejoin="round" 
              className="lucide lucide-sun">
              <circle cx="12" cy="12" r="4"/>
              <path d="M12 2v2"/>
              <path d="M12 20v2"/>
              <path d="m4.93 4.93 1.41 1.41"/>
              <path d="m17.66 17.66 1.41 1.41"/>
              <path d="M2 12h2"/>
              <path d="M20 12h2"/>
              <path d="m6.34 17.66-1.41 1.41"/>
              <path d="m19.07 4.93-1.41 1.41"/>
            </svg>
        ) : (
            <svg xmlns="http://www.w3.org/2000/svg"
              width="24" 
              eight="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              className="lucide lucide-moon">
              <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"/>
            </svg>
        )}
      </button>

      <div className={`flex-grow flex flex-col items-center transition-all duration-700 ${
        !searched ? 'justify-center' : 'pt-16'}`}>

        <motion.div
          layout
          className="flex flex-col items-center"
        >
          <motion.h1
            layout
            onClick={logoClick}
            className={`cursor-pointer font-extrabold transition-all duration-700 text-center whitespace-nowrap ${
              searched ? "text-3xl sm:text-4xl" : "text-[12vw] sm:text-[8vw] md:text-[6vw] lg:text-[4vw]"
            } ${
                darkMode
                ? glow
                ? "drop-shadow-[0_0_20px_white]"
                : ""
                : "text-black " + (glow ? "drop-shadow-[0_0_20px_black]" : "")
            }`}
          >
            CE URMEAZĂ?
          </motion.h1>

          <motion.p
            layout
            className={`font-medium transition-all duration-700 ${
              searched ? "opacity-0" : "text-sm sm:text-lg mt-2 opacity-70"
            }`}
          >
            {displayedSubtitle}
          </motion.p>

          <SearchBar
            searchText={searchText}
            setSearchText={setSearchText}
            searched={searched}
            setSearched={setSearched}
            inputRef={inputRef}
            universities={universities}
            setResults={setResults}
            startQuiz={startQuiz}
            showQuiz={showQuiz}
            darkMode={darkMode}
          />
        </motion.div>

        {searched && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 20 }}
            transition={{ duration: 0.5 }}
            className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3 w-full max-w-5xl p-4 z-10"
          >
            {results.map((f) => (
              <motion.div
                key={f.name}
                onClick={() => setSelectedUniversity(f)}
                className={`relative p-6 rounded-2xl border cursor-pointer overflow-hidden transition-all shadow-lg hover:shadow-2xl ${
                  darkMode
                  ? "bg-slate-800 border-slate-600 text-white"
                  : "bg-white border-gray-300 text-gray-900"
                }`}
                whileHover={{ scale: 1.02 }}
              >
                <motion.div
                  className="absolute inset-0 -m-[2px] rounded-2xl pointer-events-none"
                  initial={{ opacity: 0, scale: 0.95 }}
                  whileHover={{ opacity: 1, scale: 1.05 }}
                  transition={{ duration: 0.3, ease: "easeOut" }}
                  style={{
                    border: "2px solid #22d3ee",
                    boxShadow: "0 0 10px rgba(34, 211, 238, 0.7)",
                  }}
                />
                <h2 className="font-bold text-xl relative z-10">{f.name}</h2>
                <div className="flex flex-wrap gap-2 mt-2">
                  <div className={`px-3 py-1 rounded-full text-sm font-medium flex items-center ${
                    darkMode 
                    ? "bg-cyan-600 text-white" 
                    : "bg-cyan-500 text-white"}`}>
                    <svg 
                      xmlns="http://www.w3.org/2000/svg" 
                      width="16"
                      height="16" 
                      viewBox="0 0 24 24" 
                      fill="none" 
                      stroke="currentColor" 
                      strokeWidth="2" 
                      strokeLinecap="round" 
                      strokeLinejoin="round" 
                      className="lucide lucide-map-pin-icon lucide-map-pin mr-1"
                    >
                      <path d="M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0"/>
                      <circle cx="12" cy="10" r="3"/>
                  </svg>
                  {f.location}
                    <div className="absolute top-full left-1/2 -translate-x-1/2 mt-2 px-3 py-1 bg-gray-800 text-white text-xs rounded-lg opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none whitespace-nowrap z-50">
                     Click pentru a vedea pe hartă
                    </div>
                  </div> 
                  <div className={`px-3 py-1 rounded-full text-sm font-medium flex items-center ${
                    darkMode 
                    ? "bg-cyan-600 text-white" 
                    : "bg-cyan-500 text-white"}`}>
                    <svg xmlns="http://www.w3.org/2000/svg" 
                    width="24" 
                    height="24" 
                    viewBox="0 0 24 24" 
                    fill="none" 
                    stroke="currentColor" 
                    stroke-width="2" 
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    class="lucide lucide-graduation-cap-icon lucide-graduation-cap"
                    >
                      <path d="M21.42 10.922a1 1 0 0 0-.019-1.838L12.83 5.18a2 2 0 0 0-1.66 0L2.6 9.08a1 1 0 0 0 0 1.832l8.57 3.908a2 2 0 0 0 1.66 0z"/>
                      <path d="M22 10v6"/>
                      <path d="M6 12.5V16a6 3 0 0 0 12 0v-3.5"/>
                    </svg>
                  {f.university} 
                  </div> 
                  <div className={`px-3 py-1 rounded-full text-sm font-medium flex items-center ${
                    darkMode 
                    ? "bg-cyan-600 text-white" 
                    : "bg-cyan-500 text-white"}`}>
                    <svg 
                      xmlns="http://www.w3.org/2000/svg" 
                      width="16"
                      height="16" 
                      viewBox="0 0 24 24" 
                      fill="none" 
                      stroke="currentColor" 
                      strokeWidth="2" 
                      strokeLinecap="round" 
                      strokeLinejoin="round" 
                      className="lucide lucide-banknote-icon lucide-banknote mr-1"
                    >
                      <rect width="20" height="12" x="2" y="6" rx="2"/>
                      <circle cx="12" cy="12" r="2"/>
                      <path d="M6 12h.01M18 12h.01"/>
                    </svg>
                    Salarii: {f.salary.min} - {f.salary.max} RON
                  </div>
                </div>
              </motion.div>
            ))} 
          </motion.div>
        )}
      </div>

      <AnimatePresence>
        {selectedUniversity && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 flex items-center justify-center z-50 bg-black/40"
            onClick={(e) =>
              e.target === e.currentTarget && setSelectedUniversity(null)
            }
          >
            <motion.div
              initial={{ scale: 0.8 }}
              animate={{ scale: 1 }}
              exit={{ scale: 0.8 }}
              transition={{ duration: 0.3 }}
              className={`p-8 rounded-3xl max-w-3xl w-full mx-4 relative shadow-2xl overflow-y-auto max-h-[90vh] ${
                darkMode ? "bg-slate-900 text-white" : "bg-white text-gray-900"
              }`}
            >
              <button
                onClick={() => setSelectedUniversity(null)}
                className={`absolute top-4 right-4 z-20 w-10 h-10 flex items-center justify-center rounded-full transition-colors text-xl ${
                  darkMode
                  ? 'bg-slate-700 text-white hover:bg-slate-600'
                  : 'bg-gray-200 text-gray-900 hover:bg-gray-300'}`}
              >
                ✕
              </button>
              <div className="flex flex-col items-center mb-6 text-center">
                  <span className={`p-4 rounded-full mb-4 ${
                    darkMode
                    ? 'bg-slate-800' : 'bg-gray-200'}`}>
                    <img src={icon} className="w-12 h-12 text-cyan-500" />
                  </span>
                  <h2 className="text-3xl font-bold">{selectedUniversity.name}</h2>
              </div>
              
              <div className="flex flex-col gap-4">
                  <InfoCard
                      title="In cadrul:"
                      icon={
                        <svg xmlns="http://www.w3.org/2000/svg" 
                          width="16"
                          height="16" 
                          viewBox="0 0 24 24" 
                          fill="none" 
                          stroke="currentColor" 
                          strokeWidth="2" 
                          strokeLinecap="round" 
                          strokeLinejoin="round" 
                          className="lucide lucide-map-pin-icon lucide-map-pin mr-1"
                        >
                      <path d="M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0"/>
                      <circle cx="12" cy="10" r="3"/>
                  </svg>
                      }
                  >
                      <p>{selectedUniversity.university}</p>
                  </InfoCard>
                  <InfoCard
                      title="Durata studiilor:"
                      icon={
                        <svg xmlns="http://www.w3.org/24/24" 
                          width="24" 
                          height="24"
                          viewBox="0 0 24 24"
                          fill="none"
                          stroke="currentColor"
                          strokeWidth="2" 
                          strokeLinecap="round" 
                          strokeLinejoin="round" 
                          className="lucide lucide-clock">
                          <circle cx="12" cy="12" r="10"/>
                          <path d="M12 6v6l4 2"/>
                        </svg>
                      }
                  >
                      <p>{selectedUniversity.details.duration} ani</p>
                  </InfoCard>

                  <InfoCard
                      title="Ce studiezi:"
                      icon={
                        <svg xmlns="http://www.w3.org/2000/svg"
                          width="24" 
                          height="24" 
                          viewBox="0 0 24 24" 
                          fill="none" 
                          stroke="currentColor" 
                          strokeWidth="2" 
                          strokeLinecap="round" 
                          strokeLinejoin="round" 
                          className="lucide lucide-book-open">
                          <path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/>
                          <path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/>
                        </svg>
                      }
                  >
                      <p>{selectedUniversity.details.study}</p>
                  </InfoCard>

                  {selectedUniversity.details.jobs && (
                      <InfoCard
                          title="Salarii medii per job:"
                          icon={
                          <svg xmlns="http://www.w3.org/2000/svg"
                            width="24"
                            height="24"
                            viewBox="0 0 24 24" 
                            fill="none" 
                            stroke="currentColor" 
                            stroke-width="2" 
                            stroke-linecap="round" 
                            stroke-linejoin="round" 
                            class="lucide lucide-banknote-icon lucide-banknote"
                          >
                            <rect width="20" height="12" x="2" y="6" rx="2"/>
                            <circle cx="12" cy="12" r="2"/>
                            <path d="M6 12h.01M18 12h.01"/>
                          </svg>
                          }
                      >
                          {selectedUniversity.details.jobs.map((job) => (
                              <div
                                  key={job.name}
                                  className={`mt-2 p-3 rounded-lg shadow-inner ${
                                    darkMode ? "bg-slate-700" : "bg-gray-200"
                                  }`}
                              >
                                  <p>
                                    <b>{job.name}</b>
                                  </p>
                                  <p className="text-sm opacity-80">
                                    Salariu: {job.salary}
                                  </p>
                              </div>
                          ))}
                      </InfoCard>
                  )}
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      <AnimatePresence>
        {showQuiz && (
            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="fixed inset-0 flex items-center justify-center z-50 bg-black/40"
                onClick={(e) =>
                  e.target === e.currentTarget && closeQuiz()
                }
            >
                <motion.div
                    initial={{ scale: 0.8 }}
                    animate={{ scale: 1 }}
                    exit={{ scale: 0.8 }}
                    transition={{ duration: 0.3 }}
                    className={`p-8 rounded-3xl max-w-3xl w-full mx-4 relative shadow-2xl overflow-y-auto max-h-[90vh] ${
                      darkMode ? "bg-slate-900 text-white" : "bg-white text-gray-900"
                    }`}
                >
                    <button
                      onClick={closeQuiz}
                      className={`absolute top-4 right-4 z-20 w-10 h-10 flex items-center justify-center rounded-full transition-colors text-xl ${
                        darkMode 
                        ? 'bg-slate-700 text-white hover:bg-slate-600' 
                        : 'bg-gray-200 text-gray-900 hover:bg-gray-300'}`}
                    >
                        ✕
                    </button>
                    {quizResult ? (
                        <>
                          <h2 className="text-3xl font-bold mb-4">Recomandare pentru tine</h2>
                          <p className="text-xl font-semibold mb-4">
                            {quizResult.name}
                          </p>
                          <p>{quizResult.details.study}</p>
                          <button
                            onClick={() => {
                              setSelectedUniversity(quizResult);
                              closeQuiz();
                            }}
                          className={`mt-6 px-6 py-3 rounded-full font-semibold shadow-lg transition-all duration-300 ${
                            darkMode
                            ? "bg-cyan-700 hover:bg-cyan-600 text-white"
                            : "bg-cyan-500 hover:bg-cyan-400 text-white"
                          }`}
                            >
                              Vezi detalii
                            </button>
                        </>
                    ) : (
                        <>
                            <h3 className="text-xl font-semibold mb-6 text-center">
                              {currentQuestion.questionText}
                            </h3>
                            {currentQuestion.type === "multiple-choice" ? (
                              <div className="flex flex-col gap-4">
                                {currentQuestion.options.map((option, index) => (
                                  <button
                                    key={index}
                                    onClick={() => quizAnswer(option.scores)}
                                    className={`px-6 py-4 rounded-xl shadow-md font-medium text-lg transition-all duration-300 text-center ${
                                      darkMode ? "bg-slate-800 hover:bg-cyan-700 text-white" : "bg-gray-100 hover:bg-gray-200 text-gray-900"
                                    }`}
                                  >
                                  {option.text}
                                    </button>
                                  ))}
                                </div>
                            ) : (
                                <div className="flex flex-col items-center gap-4">
                                  <input
                                    type="range"
                                    min={currentQuestion.min}
                                    max={currentQuestion.max}
                                    step={currentQuestion.step}
                                    value={salaryRange}
                                    onChange={(e) => setSalaryRange(Number(e.target.value))}
                                    className="w-full h-2 rounded-lg appearance-none cursor-pointer bg-cyan-400 dark:bg-cyan-600"
                                    style={{'--tw-shadow':'0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)'}}
                                  />
                                  <div className="flex justify-between w-full text-sm mt-2">
                                    <span>2500 RON</span>
                                    <span className={`font-extrabold text-lg transition-all duration-300 ${darkMode ? 'text-cyan-600' : 'text-cyan-600'}`}>
                                      {salaryRange} RON
                                    </span>
                                    <span>10000 RON</span>
                                  </div>
                                  <button
                                    onClick={calculateResult}
                                    className={`px-6 py-3 rounded-full font-semibold shadow-lg mt-4 transition-all duration-300 ${
                                      darkMode ? "bg-cyan-700 hover:bg-cyan-600 text-white" : "bg-cyan-500 hover:bg-cyan-400 text-white"
                                    }`}
                                  >
                                    Vezi rezultatul
                                  </button>
                                </div>
                            )}
                            <p className="text-sm text-center mt-4 opacity-50">
                                Întrebarea {currentQuestionIndex + 1} din {quizQuestions.length}
                            </p>
                        </>
                    )}
                </motion.div>
            </motion.div>
        )}
      </AnimatePresence>

      <footer
        className={`w-full py-6 mt-12 flex flex-col items-center justify-center gap-1 text-center transition-all duration-500 ${
          darkMode ? "bg-slate-900 text-gray-200" : "bg-gray-100 text-gray-900"
        }`}
      >
        <p className="font-semibold text-lg">© 2025 KEYRIF</p>
        <a className="text-sm opacity-80" href="https://github.com/keyrif/ce-urmeaza">
          Pagina Proiect Github
        </a>
        <a className="text-sm opacity-80" href="https://www.paylab.ro/">
          Sursa salarii
        </a>
      </footer>
    </div>
  );
}
export default App;

// src/App.vue
<template>
  <div :class="['min-h-screen', 'flex', 'flex-col', 'relative', 'font-sans', 'transition-colors', 'duration-500', 'ease-in-out', darkMode ? 'bg-slate-950 text-slate-100' : 'bg-slate-100 text-slate-950', 'z-10', 'select-none']">
    <div
      :class="['absolute', 'top-0', 'right-0', 'w-full', 'h-full', 'rounded-bl-full', 'transform', 'transition-transform', 'duration-[1000ms]', 'ease-in-out', 'z-0', 'origin-top-right', {'scale-x-[2] scale-y-[2]': !isAnimating, 'scale-x-[0] scale-y-[0]': isAnimating}]"
      :style="{ 'background-color': darkMode ? '#0f172a' : '#f1f5f9' }"
    ></div>
    <button
      v-if="!isSidePanelVisible"
      @click="toggleDarkModeWithAnimation"
      :class="['fixed', 'top-4', 'right-4', 'p-2', 'rounded-full', 'shadow-lg', 'transition-colors', 'duration-500', 'ease-in-out', 'z-20', 'z-[30]', darkMode ? 'bg-slate-800 text-slate-100 hover:bg-slate-700' : 'bg-slate-200 text-slate-800 hover:bg-slate-300']"
    >
      <svg v-if="darkMode" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" />
      </svg>
      <svg v-else xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 3v1m0 16v1m9-9h-1m-16 0H3m15.364 6.364l-.707.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
      </svg>
    </button>

    <button
      @click="toggleSidePanel"
      :class="['fixed', 'top-20', 'right-4', 'p-2', 'rounded-full', 'shadow-lg', 'transition-colors', 'duration-500', 'ease-in-out', 'z-[31]', 'transform', darkMode ? 'bg-slate-800 text-slate-100 hover:bg-slate-700' : 'bg-slate-200 text-slate-800 hover:bg-slate-300', isSidePanelVisible ? 'translate-x-[-275px] md:translate-x-[-375px]' : 'translate-x-0']"
    >
      <svg v-if="isSidePanelVisible" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
      </svg>
      <svg v-else xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
      </svg>
    </button>

    <aside
      :class="['fixed', 'top-0', 'right-0', 'h-full', 'w-[250px]', 'md:w-[350px]', 'backdrop-blur-xl', 'shadow-2xl', 'z-[29]', 'transform', 'transition-transform', 'duration-500', 'ease-in-out', {'translate-x-0': isSidePanelVisible, 'translate-x-full': !isSidePanelVisible}, darkMode ? 'bg-slate-800/80' : 'bg-slate-200/80']"
    >
      <div :class="['p-6', 'h-full', 'flex', 'flex-col', 'justify-start', darkMode ? 'text-slate-100' : 'text-slate-950']">
        <h2 class="text-3xl font-bold mb-4">Detalii site:</h2>
        <p :class="['text-sm', darkMode ? 'text-slate-400' : 'text-slate-600']">
          <p class="text-sm font-light">Made by <a href="https://github.com/Keyrif" target="_blank" class="text-blue-500 hover:underline">Keyrif</a>, version: 0.8</p><br></br>
          <p class="text-sm font-light">Pagina proiect: <a href="https://github.com/Keyrif" target="_blank" class="text-blue-500 hover:underline">GITHUB</a></p><br></br>
          Surse de unde au fost preluate informatiile: 
          <br></br>- eJobs
          <Br></Br>- BestJobs
        </p>
      </div>
    </aside>
    <div :class="['w-full', 'flex', 'flex-col', 'items-center', 'justify-start', 'flex-grow', 'max-w-7xl', 'mx-auto']">
      <div class="w-full flex flex-col items-center justify-start p-4">
        <h1 
          :class="['font-extrabold', 'transition-all', 'duration-700', 'ease-in-out', 'text-center', 'cursor-pointer', 'relative', 'select-none', isContentVisible ? 'text-4xl md:text-5xl mt-[10vh]' : 'text-6xl sm:text-7xl md:text-9xl mt-[calc(40vh-100px)]', logoClicked ? (darkMode ? 'animate-glow-white' : 'animate-glow-black') : '', darkMode ? 'text-slate-100' : 'text-slate-950']"
          @click="handleLogoClick"
        >
          CE URMEAZĂ?
        </h1>
        <div v-if="!isContentVisible" class="mt-4">
          <span
            :class="[
              'text-lg',
              'md:text-xl',
              'font-semibold',
              'text-slate-400',
              'overflow-hidden',
              'whitespace-nowrap',
              'relative',
              'animate-text'
            ]"
          >
            INFORMAȚII DESPRE FACULTĂȚI SI JOBURI
          </span>
        </div>
        
        <SearchBar
          ref="searchBarRef"
          :faculties="faculties"
          :darkMode="darkMode"
          @update:filteredFaculties="updateFilteredFaculties"
          @update:hasSearched="updateHasSearched"
          @update:isScrolledDown="updateIsScrolledDown"
        />
        <div :class="['w-full', 'mt-4', 'md:mt-16', 'flex', 'flex-col', 'items-center', 'justify-center', 'transition-opacity', 'duration-500', 'animate-bounce-slow', { 'opacity-0': isContentVisible, 'opacity-100': !isContentVisible }]">
          <p class="text-lg font-semibold mb-2 text-center">Scrollează pentru a vedea toate facultățile.</p>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="h-8 w-8 mx-auto animate-scroll">
            <path d="M12 4.5A7.5 7.5 0 0 0 4.5 12a7.5 7.5 0 0 0 7.5 7.5 7.5 7.5 0 0 0 7.5-7.5A7.5 7.5 0 0 0 12 4.5zm0-1.5a9 9 0 1 1 0 18 9 9 0 0 1 0-18zm.25 10.75V15h-.5v-1.75H9.5L12 10.75l2.5 2.5z"/>
          </svg>
        </div>
        <div v-if="isContentVisible" :class="['mt-4', 'font-semibold', 'text-base', 'text-center', 'transition-colors', 'duration-500', darkMode ? 'text-slate-400' : 'text-slate-600']">
          <span v-if="!hasSearched">
            Total facultăți: {{ faculties.length }}
          </span>
          <span v-else>
            Am găsit {{ filteredFaculties.length }} facultăți.
          </span>
        </div>
        
        <div 
          :class="['mt-12', 'flex', 'flex-col', 'items-center', 'p-8', 'transition-opacity', 'duration-700', 'ease-in-out', 'delay-500']"
          :style="{ opacity: isContentVisible ? 1 : 0 }"
        >
          <div :class="['grid', 'grid-cols-1', 'md:grid-cols-2', 'gap-8', 'w-full', 'max-w-7xl']">
            <template v-if="filteredFaculties.length > 0">
              <div
                v-for="(fac, index) in filteredFaculties"
                :key="index"
                :class="['p-8', 'rounded-2xl', 'backdrop-blur-md', 'border', 'text-center', 'transition-all', 'duration-300', 'transform', 'w-full', 'min-h-[150px]', 'flex', 'flex-col', 'justify-center', 'shadow-lg', 'hover:shadow-xl', 'relative', 'group', 'hover:scale-105', darkMode ? 'bg-slate-800/60 border-slate-700' : 'bg-slate-200/60 border-slate-300']"
                @click="setSelectedFaculty(fac)"
              >
                <h3 :class="['font-semibold', 'text-2xl', darkMode ? 'text-white' : 'text-slate-950']">{{ fac.name }}</h3>
                <p :class="['mt-1', darkMode ? 'text-slate-400' : 'text-slate-600']">{{ fac.location }}</p>
              </div>
            </template>
            <div v-else-if="hasSearched" :class="['col-span-full', 'text-center', 'text-lg', darkMode ? 'text-slate-400' : 'text-slate-600']">
              Nu am găsit facultăți care să se potrivească.
            </div>
          </div>
        </div>
      </div>
    </div>
    <FacultyDetailsPopup 
      v-if="selectedFaculty"
      :faculty="selectedFaculty" 
      @close="setSelectedFaculty(null)" 
      :darkMode="darkMode"
    />

  </div>
</template>

<script setup>
import { ref, watch, computed, onMounted } from 'vue';
import FacultyDetailsPopup from './components/FacultyDetailsPopup.vue';
import SearchBar from './components/SearchBar.vue';
const faculties = ref([]);
const selectedFaculty = ref(null);
const logoClicked = ref(false);
const isAnimating = ref(false);
const isSidePanelVisible = ref(false); 
const filteredFaculties = ref([]);
const hasSearched = ref(false); 
const isScrolledDown = ref(false); 
const searchBarRef = ref(null); 

const isContentVisible = computed(() => hasSearched.value || isScrolledDown.value);

const dummyFaculties = [
    { name: 'Facultatea de Informatică', location: 'București' },
    { name: 'Facultatea de Electronică, Telecomunicații și Tehnologia Informației', location: 'Cluj-Napoca' },
    { name: 'Facultatea de Litere', location: 'Iași' },
    { name: 'Facultatea de Științe Politice', location: 'Timișoara' },
    { name: 'Facultatea de Drept', location: 'Brașov' },
    { name: 'Facultatea de Medicină', location: 'Craiova' },
    { name: 'Facultatea de Jurnalism și Științele Comunicării', location: 'Constanța' },
    { name: 'Facultatea de Matematică și Informatică', location: 'București' },
    { name: 'Facultatea de Istorie', location: 'Sibiu' },
    { name: 'Facultatea de Istorie', location: 'Sibiu' },
];

const getInitialDarkMode = () => {
  const savedMode = localStorage.getItem('darkMode');
  return savedMode !== null ? JSON.parse(savedMode) : false;
};

const darkMode = ref(getInitialDarkMode());

watch(darkMode, (newValue) => {
  localStorage.setItem('darkMode', JSON.stringify(newValue));
});

const handleLogoClick = () => {
  if (searchBarRef.value) {
    searchBarRef.value.reset();
  }
  hasSearched.value = false;
  isScrolledDown.value = false;
  logoClicked.value = true;
  window.scrollTo({ top: 0, behavior: 'smooth' });
  setTimeout(() => {
    logoClicked.value = false;
  }, 750);
};

const setSelectedFaculty = (fac) => {
  selectedFaculty.value = fac;
};
const toggleDarkModeWithAnimation = () => {
  isAnimating.value = true;
  setTimeout(() => {
    darkMode.value = !darkMode.value;
    isAnimating.value = false;
  }, 500);
};

const toggleSidePanel = () => {
  isSidePanelVisible.value = !isSidePanelVisible.value;
};

const updateFilteredFaculties = (newFaculties) => {
  filteredFaculties.value = newFaculties;
};

const updateHasSearched = (newHasSearched) => {
  hasSearched.value = newHasSearched;
};

const updateIsScrolledDown = (newIsScrolledDown) => {
  isScrolledDown.value = newIsScrolledDown;
};

onMounted(() => {
  faculties.value = dummyFaculties;
  filteredFaculties.value = dummyFaculties;
});
</script>

<style>
  html, body {
    margin: 0;
    min-height: 100vh;
  }
  body {
    overflow-x: hidden;
  }
  
  @keyframes glow-white {
    0% {
      text-shadow: 0 0 5px rgba(255, 255, 255, 0.2), 0 0 10px rgba(255, 255, 255, 0.2);
    }
    50% {
      text-shadow: 0 0 20px rgba(255, 255, 255, 0.8), 0 0 30px rgba(255, 255, 255, 0.8);
    }
    100% {
      text-shadow: 0 0 5px rgba(255, 255, 255, 0.2), 0 0 10px rgba(255, 255, 255, 0.2);
    }
  }

  @keyframes glow-black {
    0% {
      text-shadow: 0 0 5px rgba(0, 0, 0, 0.2), 0 0 10px rgba(0, 0, 0, 0.2);
    }
    50% {
      text-shadow: 0 0 20px rgba(0, 0, 0, 0.8), 0 0 30px rgba(0, 0, 0, 0.8);
    }
    100% {
      text-shadow: 0 0 5px rgba(0, 0, 0, 0.2), 0 0 10px rgba(0, 0, 0, 0.2);
    }
  }
  
  @keyframes scrollAnimation {
    0% { transform: translateY(0); opacity: 1; }
    50% { transform: translateY(12px); opacity: 0; }
    100% { transform: translateY(0); opacity: 1; }
  }
  .animate-scroll {
    animation: scrollAnimation 1.5s ease-in-out infinite;
  }

  @keyframes bounce-slow {
    0%, 100% {
      transform: translateY(0);
      animation-timing-function: cubic-bezier(0, 0, 0.2, 1);
    }
    50% {
      transform: translateY(-8px);
      animation-timing-function: cubic-bezier(0.8, 0, 1, 1);
    }
  }

  .animate-bounce-slow {
    animation: bounce-slow 2s infinite;
  }

  .animate-glow-white {
    animation: glow-white 0.4s ease-in-out;
  }
  .animate-glow-black {
    animation: glow-black 0.4s ease-in-out;
  }
  
  @keyframes fadeIn {
    from { opacity: 0; }
    to { opacity: 1; }
  }
  
  @keyframes zoomIn {
    from { transform: scale(0.95); opacity: 0; }
    to { transform: scale(1); opacity: 1; }
  }

  .group:hover::before {
    transform: scale(1);
    opacity: 1;
  }
  
  .group::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    border: 3px solid theme('colors.cyan.400');
    border-radius: theme('borderRadius.2xl');
    transform: scale(0.9);
    opacity: 0;
    transition: transform 0.3s ease-out, opacity 0.3s ease-out;
    pointer-events: none; 
  }

  .group:active::before {
    border-color: theme('colors.cyan.300');
    transform: scale(1.05);
    transition-duration: 0.1s;
  }

  @keyframes animate-text {
    0% { width: 0; border-right: 3px solid; } 
    10% { width: 100%; } 
    70% { width: 100%; border-right: none; }
    80% { width: 0; border-right: 3px solid; } 
    100% { width: 0; border-right: none; } 
  }
  .animate-text {
    animation: animate-text 12s steps(20) infinite;
    display: inline-block;
  }
</style>
